Update CONTRIBUTING.md
duaimei/civic_hacking_hub pull request #75
Opened 2021-10-06 17:05 UTC by eshaanagarwal

Changed CONTRIBUTING.md as requested  in #40

2021-10-07 03:08 UTC, amycommits requested changes

2021-10-07 03:08 UTC, amycommits commented on CONTRIBUTING.md
> +$ git checkout -b
would you mind putting something like:
$ git checkout -b \<your-branch-name\>

2021-10-07 03:08 UTC, amycommits commented on CONTRIBUTING.md
> +$ git checkout -b
The trick is you need to add a \\ in front of the \<

2021-10-07 03:30 UTC, eshaanagarwal commented on CONTRIBUTING.md
> +$ git checkout -b
Sure! I will make the changes.

2021-10-07 04:07 UTC, eshaanagarwal commented
@duaimei I have made the required changes! Pls review.

2021-10-12 01:42 UTC, amycommits approved these changes

2021-10-12 01:42 UTC, merged

2021-10-12 01:42 UTC, amycommits commented
Thank you, sorry that took so long!